In [1]:
import numpy as np

In [2]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
y = np.zeros((2, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
x+y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  2
shape =  (2, 3)
size =  6


In [6]:
w = np.array([[11, 12], [13, 14], [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [7]:
w.shape

(3, 2)

In [8]:
z = np.arange(1, 4)
z

array([1, 2, 3])

In [9]:
newArray = np.column_stack((z, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

In [10]:
newArray.transpose()

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

In [11]:
newArray -= 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [12]:
newArray.min()

0

In [13]:
newArray.max()

15

In [14]:
newArray[0]

array([ 0, 10, 11])

In [15]:
newArray[1][1]

12

In [16]:
newArray[[0,1], [0,2]]

array([ 0, 13])

In [17]:
newArray.shape

(3, 3)

In [18]:
newArray.reshape(9, 1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

In [19]:
newArray.reshape(3, 2) # error because we have 9 elements not 6

ValueError: cannot reshape array of size 9 into shape (3,2)

In [20]:
for row in newArray:
    for item in row:
        print(item)

0
10
11
1
12
13
2
14
15
